from typing import Any

def parse_lxcat_text(text: str) -> list[dict[str, Any]]: ...
def parse_lxcat_file(path: str) -> list[dict[str, Any]]: ...
def validate_cross_section(section: dict[str, Any]) -> None: ...
def interp_sigma(
    energy: list[float], values: list[float], threshold: float, eps: list[float]
) -> list[float]: ...
def validate_fractions(fractions: list[float]) -> float: ...
def number_density(
    pressure_pa: float | None, temperature_k: float, number_density: float | None
) -> float: ...
def mass_ratio_from_amu(mass_amu: float) -> float: ...
def mesh_data(eps_max_ev: float, d_eps_ev: float, n_theta: int) -> dict[str, Any]: ...
def mesh_data_from_edges(edges_ev: list[float], n_theta: int) -> dict[str, Any]: ...
def graded_energy_edges(
    eps_max_ev: float, d_eps_min_ev: float, eps_uniform_ev: float
) -> list[float]: ...

class CoreSolver:
    def __init__(
        self,
        eps_max_ev: float,
        d_eps_ev: float,
        n_theta: int,
        safety: float,
        parallel: bool,
        number_density: float,
        kinds: list[str],
        gas_names: list[str],
        process_names: list[str],
        fractions: list[float],
        thresholds_ev: list[float],
        mass_ratios: list[float],
        sigma_rows: list[list[float]],
    ) -> None: ...
    @staticmethod
    def from_mixture(
        gases: list[dict[str, Any]],
        number_density: float,
        temperature_k: float,
        excitation_temperature_k: float | None,
        transition_energy_ev: float,
        energy_edges: list[float] | None,
        eps_max_ev: float,
        d_eps_ev: float,
        n_theta: int,
        safety: float,
        parallel: bool,
        superelastic: bool,
        gas_heating: bool,
    ) -> CoreSolver: ...
    def mesh_data(self) -> dict[str, Any]: ...
    def processes(self) -> list[dict[str, Any]]: ...
    def initial_maxwell(self, temperature_ev: float) -> list[float]: ...
    def auto_dt(self, acceleration: float) -> float: ...
    def advection_apply(self, state: list[float], xi: float, sign: int) -> list[float]: ...
    def collision_apply(self, state: list[float]) -> list[float]: ...
    def fixed_steps(
        self,
        state: list[float],
        acceleration: float,
        dt: float,
        xi: float,
        sign: int,
        steps: int,
    ) -> list[float]: ...
    def solve_dc(self, *args: Any) -> dict[str, Any]: ...
    def solve_dc_many(self, *args: Any) -> list[dict[str, Any]]: ...
    def solve_rf(self, *args: Any) -> dict[str, Any]: ...
